CREATE TABLE CATALOGUE (
     ID         SERIAL PRIMARY KEY,
     REF	    VARCHAR(50),
     TITRE	    VARCHAR(255),
     PRIX	    FLOAT
);
INSERT INTO CREATE TABLE CATALOGUE (
 (REF,TITRE,PRIX) VALUES ( 'X1','Linux',10.5);